### ISSUE TITLE
fix(integration): network_adapter.cpp Result<> misuse

### ISSUE THREAD

**Issue by kcenon** [kcenon/pacs_system#1096]
## What

Integration Tests fail on all three platforms (ubuntu-24.04, macos-14, windows-2022) due to compilation errors in `src/integration/network_adapter.cpp`. The code uses the `->` operator directly on a `Result<std::shared_ptr<i_protocol_client>>` wrapper, which is not a pointer type.

**Affected lines**: 94, 98, 110, 118, 125

**Error sample**:
```
src/integration/network_adapter.cpp:94:15: error: base operand of '->' has non-pointer type
  'kcenon::common::Result<std::shared_ptr<kcenon::network::interfaces::i_protocol_client>>'
```

## Why

`kcenon::common::Result<T>` is an either/optional wrapper, not a pointer. To access the underlying value, callers must first check `is_err()` / `is_ok()` and then call `.value()` or equivalent. Direct use of `->` bypasses the Result abstraction and fails to compile.

This blocks the `Integration Tests` workflow on every PR that builds against the current `network_system` dependency, including PR #1094 (which only touched cert files — unrelated).

## Where

- File: `src/integration/network_adapter.cpp`
- Lines: 94, 98, 110, 118, 125
- Workflow: `Integration Tests` → `Build & Unit Tests` (fails on all OSes)
- Related failing CI run (example): https://github.com/kcenon/pacs_system/actions/runs/24349458253

### Reproduction
```bash
cmake -S . -B build -G Ninja
cmake --build build --target pacs_integration
# Observe compile error at network_adapter.cpp:94
```

### Proposed Fix
Refactor to extract the `shared_ptr` from the `Result` before use:

```cpp
auto client_result = facade.create_client(client_cfg);
if (client_result.is_err()) {
    return Result<session_ptr>(error_info("Connection failed: " + client_result.error().message));
}
auto client = client_result.value();   // <-- extract once
client->set_connected_callback(...);   // <-- now client is shared_ptr, -> is valid
```

Note: a local copy of this file already shows this pattern applied, but the version in the PR #1094 branch (and likely `develop`'s build tree after the `network_system` API change) still has the broken code path. Audit all call sites in `src/integration/` that consume `create_client` / `create_server` return values.

### Acceptance Criteria
- [ ] All five `->` misuse sites in `network_adapter.cpp` fixed
- [ ] `Integration Tests / Build & Unit Tests` passes on ubuntu-24.04, macos-14, windows-2022
- [ ] No regression in other `pacs_integration` consumers
- [ ] Grep confirms no other `Result<shared_ptr<...>>->` patterns remain

## Context

Observed on `develop` branch (run 24349440326 on commit `43588580`) — pre-existing, **not** caused by PR #1094. Splitting into a dedicated issue per `Surgical Precision` principle so the cert-exclusion PR remains scoped.

**Comment by kcenon** [comment]
## Investigation Update

This issue was retriaged and the original description is inconsistent with the state at the pinned network_system SHA used by CI.

**Findings**
- The CI pins network_system at SHA `093691d9523265d672880e2cb7c0ea0e4463a8f8` (see `.github/actions/checkout-kcenon-deps/action.yml`).
- At that SHA, `kcenon::network::facade::tcp_facade::create_client` returns `std::shared_ptr<interfaces::i_protocol_client>` directly — **not** `Result<std::shared_ptr<...>>`.
- The current code in `src/integration/network_adapter.cpp` (shared_ptr null check + `->` calls) is therefore correct for the pinned SHA.
- The Result<> wrapping appears in network_system HEAD only after commit `8d0679e6` ("refactor(facade): migrate all facade APIs from throw to Result<T> (#952)"), which is newer than the current pin.

**Attempt**
PR #1110 applied the Result<> extraction pattern and failed to compile on all CI platforms with:
```
error: no member named 'is_err' in 'std::shared_ptr<kcenon::network::interfaces::i_protocol_client>'
```
PR was closed, branch deleted, no change merged.

**Recommendation**
This issue should be re-scoped as a tracking item for the pin-bump work: when `NETWORK_SYSTEM_SHA` is bumped past `8d0679e6`, network_adapter.cpp will need the Result<> extraction pattern. Until then the existing code is correct and there is no build regression.

@kcenon please confirm whether to close as "outdated" or keep open as a reminder tied to the pin bump.

**Comment by kcenon** [comment]
Closing as **resolved upstream**.

When this issue was filed (run 24349458253, 2026-04-14), the published
vcpkg port of `kcenon-network-system` exposed
`tcp_facade::create_client() -> Result<std::shared_ptr<i_protocol_client>>`,
which made `client->` on that value a compile error at lines 94/98/110/118/125.

Since then, the vcpkg port has been updated so `create_client()` returns
`std::shared_ptr<i_protocol_client>` directly. Under the current port the
existing code on `develop` compiles cleanly — `if (!client)` resolves via
`shared_ptr::operator bool()`, and `client->` dereferences the `shared_ptr`.

Verified on the latest `develop` run: `Integration Tests` is `success`.

Attempted remediation PR #1111 was closed — adding `.is_err()` / `.value()`
broke the build because `std::shared_ptr` has no such members.

**Caveat for future vcpkg baseline bumps**: the source tree of
`network_system` at its HEAD reintroduces the `Result<shared_ptr<>>` return
type. The next baseline bump that pulls that newer API will re-require this
exact unwrap-the-Result fix in `network_adapter.cpp` (plus the same change
in `src/network/v2/dicom_server_v2.cpp:139`, which is currently gated by
`#ifdef PACS_WITH_NETWORK_SYSTEM`).
